### ISSUE TITLE
Move package/README.md to the top folder?

### ISSUE THREAD

**Issue by ahmedlhanafy** [GeoffCox/react-splitter#1]
Normally the home page of a project (`<root>/README.md`) has some relevant information about the project (how to install, all the docs if the library is small, sample code and so on), otherwise, it gives the feeling that it's an unfinished project. 
I see that you already did this on NPM but not here.

**Comment by GeoffCox** [comment]
I agree.  The demo and the package had node_module conflicts.  The npm publish seems to use the readme at the same level as the package/package.json.  I'll see if I can control the readme location from the publish to npm so that I can have one on the root.

**Comment by GeoffCox** [comment]
For now I've duplicated the readme at the top level and in the package folder.  The package.json claims to support a readme value, but npm publish seems to always use the one next to package.json.
