### ISSUE TITLE
Widen peer dependency range to include React 17

### ISSUE THREAD

**Issue by philborlin** [GeoffCox/react-splitter#16]
Could the peer dependency please be widened to `^16.9.36 || ^17.0.0` for both react and react-dom?

**Comment by GeoffCox** [comment]
Yes! I went and widened it to this:
"@types/react": ">=16.8.0 <19.0.0",
"@types/react-dom": ">=16.8.0 <19.0.0",

I have not yet tested it in React 18 or in strict mode. If you find issues with it, LMK.
